service: ner-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.6
  lambdaHashingVersion: 20201221
  stage: dev
  region: af-south-1

package:
   exclude:
    - node_modules/**
    - .vscode/**
    - __pycache__/**
    - .ipynb_checkpoints/**
    - (*).ipynb 

functions:
  recognize-named-entities:
    handler: handler.handle_request
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: /ner
          method: post

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    zip: true
    noDeploy: []
    useDownloadCache: true
    useStaticCache: true

plugins:
  - serverless-python-requirements
