
service: california-housing

frameworkVersion: '2'

provider:
    name: aws
    runtime: python3.6
    stage: dev
    region: us-east-2

package:
    exclude:
        - node_modules/**
        - vscode/**
        - __pycache__/**
        - .ipynb_checkpoints/**
        - (*).ipynb


functions:
    predict-price:
        handler: handler.predict
        memorySize: 512
        timeout: 30
        events:
            - http:
                method: GET
                path: /get-price
                request:
                    parameters:
                        querystrings:
                            medInc: true
                            houseAge: true
                            aveRooms: true
                            aveBedrms: true
                            population: true
                            aveOccup: true
                            latitude: true
                            longitude: true

plugins:
    - serverless-python-requirements

custom:
    pythonRequirements:
        dockerizePip: true
        slim: true
