service: parse-api

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: af-south-1

package:
  exclude:
    - node_modules/**
    - .vscode/**
    - __pycache__/**

functions:
  parse-text:
    handler: handler.handle_request
    memorySize: 1536
    timeout: 30
    events:
      - http:
          path: /parse
          method: post

custom:
  pythonRequirements:
    dcokerizePip: true
    slim: true
    zip: true
    noDeploy: []
    useDownloadCache: true
    useStaticCache: true

plugins:
  - serverless-python-requirements